// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoApi_MontagemMoveis.Data;

namespace ProjetoApi_MontagemMoveis.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220403215018_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoApi_MontagemMoveis.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoMovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoMovel")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoServico")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorOrcamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoMovel = "Guarda-roupa com 3 portas de espelho",
                            EstadoMovel = 1,
                            NomeCliente = "Barbara",
                            TipoMovel = "Guarda-Roupa",
                            TipoServico = 1,
                            ValorOrcamento = 200m,
                            status = 1
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoMovel = "Cômoda de tres gavetas",
                            EstadoMovel = 2,
                            NomeCliente = "Sonia ",
                            TipoMovel = "Cômoda",
                            TipoServico = 2,
                            ValorOrcamento = 150.50m,
                            status = 1
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoMovel = "Mesa gamer 60cm - 136cm ",
                            EstadoMovel = 1,
                            NomeCliente = "Gabriel ",
                            TipoMovel = "Mesa ",
                            TipoServico = 1,
                            ValorOrcamento = 300m,
                            status = 1
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescricaoMovel = "Mesa de 4 cadeiras",
                            EstadoMovel = 2,
                            NomeCliente = "Anahi ",
                            TipoMovel = "Mesa",
                            TipoServico = 2,
                            ValorOrcamento = 200m,
                            status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
